version: 2
updates:
  - package-ecosystem: mix
    insecure-external-code-execution: allow
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
